# ============================================================================
include:
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/defaults@release/0.2


# ============================================================================
.helm-base:
  image: $CI_REGISTRY/kerrys-learning-lab/devsecops/cicd-catalog/helm-chart:main
