# ============================================================================
spec:
  inputs:

    chart_dir:
      description:  See templates/pipeline.yml
      type: string
      default: .

    helm_dependencies:
      description:  See templates/pipeline.yml
      type: array
      default: []

    stage:
      description:  See templates/pipeline.yml
      type: string
      default: build

    needs:
      description:  See templates/pipeline.yml
      type: array
      default: []

    job_name_prefix:
      description: Optional prefix for this Job's name
      type: string
      default: ''

    job_name_suffix:
      description: Optional suffix for this Job's name
      type: string
      default: ''


  component:
    - name
    - version
    - reference


---


# ============================================================================
include:
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/defaults@release/0.2
  - local: .base.gitlab-ci.yml


# ----------------------------------------------------------------------------
"$[[ inputs.job_name_prefix ]]helm package$[[ inputs.job_name_suffix ]]":
  extends: .helm-package
  stage: $[[ inputs.stage ]]
  variables:
    COMPONENT_NAME: $[[ component.name ]]
    COMPONENT_REFERENCE: $[[ component.reference ]]
    HELM_CHART_DIR: $[[ inputs.chart_dir ]]
    CMPNT_HELM_DEPENDENCIES: "'$[[ inputs.helm_dependencies ]]'"
  needs:
    - pipeline version
    - $[[ inputs.needs ]]
