# ============================================================================
spec:
  inputs:

    # ------------------------------------------------------------------------
    chart_dir:
      description: Relative path to the chart contents (folder which contains
                   Chart.yaml)
      type: string
      default: .

    helm_dependencies:
      type: array
      default: []

    package_stage:
      description: Assigns the Pipeline stage for the 'helm package' Job
      type: string
      default: build

    package_needs:
      description: DAG specification for the 'helm package' Job
      type: array
      default: []


    # ------------------------------------------------------------------------
    # These settings affect the unit testing of the Helm chart
    unit_test_enabled:
      description:  If true, the Helm chart will be unit tested
      type: boolean
      default: true

    unit_test_chart_dir:
      description: Relative path to the chart contents to be tested (folder
                   which contains Chart.yaml).

                   Generally speaking, this will be the same value as for
                   'helm_chart_dir'.  However, when testing library
                   charts, this will usually be a different Chart directory
                   which exists specifically to use the library Chart.
      type: string
      default: .

    unit_test_file_glob:
      description: Test files glob pattern relative to 'helm_unit_test_chart_dir'
      type: string
      default: tests/*.tests.yaml

    unit_test_stage:
      description: Assigns the Pipeline stage for the 'helm unit-test' Job
      type: string
      default: test


    # ------------------------------------------------------------------------
    # These settings affect the pushed Chart
    push_destination:
      description: |
                    Determine the destination for the pushed Chart.

                    - oci -     Publish to the project's image registry
                    - package - Publish to the Project's package registry
                    - both -    Publishes to both the oci and package registries
      type: string
      options:
        - oci
        - package
        - both
      default: both

    push_stage:
      description: Assigns the Pipeline stage for the 'helm push' Job
      type: string
      default: push

    push_mode:
      description: By default, only protected refs are pushed to the Helm
                   Chart repository.  Specifying 'force' will push the Chart for
                   non-protected refs.  Specifying 'skip' will not push
                   protected refs.
      type: string
      options:
        - protected
        - skip
        - force
      default: protected


    # ------------------------------------------------------------------------
    # These settings affect all Jobs instantiated by this component
    job_name_prefix:
      description: Optional prefix for the Job names
      type: string
      default: ''

    job_name_suffix:
      description: Optional suffix for the Job names
      type: string
      default: ''


  component:
    - name
    - reference
    - version

---


# ============================================================================
include:
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/semver@release/0.2
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/release@release/0.2
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/merge-forward@release/0.2

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/helm-chart/package@$[[ component.reference ]]
    inputs:
      chart_dir: $[[ inputs.chart_dir ]]
      helm_dependencies: $[[ inputs.helm_dependencies ]]
      stage: $[[ inputs.package_stage ]]
      needs: $[[ inputs.package_needs ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/helm-chart/unit-test@$[[ component.reference ]]
    inputs:
      enabled: $[[ inputs.unit_test_enabled ]]
      chart_dir: $[[ inputs.unit_test_chart_dir ]]
      file_glob: $[[ inputs.unit_test_file_glob ]]
      stage: $[[ inputs.unit_test_stage ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]

  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/helm-chart/push@$[[ component.reference ]]
    inputs:
      chart_dir: $[[ inputs.chart_dir ]]
      destination: $[[ inputs.push_destination ]]
      mode: $[[ inputs.push_mode ]]
      stage: $[[ inputs.push_stage ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]


# ============================================================================
workflow:
  name: Helm Chart Pipeline
  rules:
    - !reference [.rules//merge-request-as-primary-workflow,  rules]
